<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Vehicle>
 */
class VehicleFactory extends Factory
{
	/**
	* Define the model's default state.
	*
	* @return array<string, mixed>
	*/
	public function definition(): array
	{
		return [
			'registration' => null,
			'active' => 1,
			'pcv' => 0,
			'datum_1_registrace' => null,
			'datum_1_registrace_cr' => null,
			'ztp' => null,
			'es_eu' => null,
			'druh_vozidla' => 'OSOBNÍ AUTOMOBIL',
			'druh_vozidla_2_r' => null,
			'kategorie_vozidla' => null,
			'tovarni_znacka' => null,
			'typ' => null,
			'varianta' => null,
			'verze' => null,
			'vin' => null,
			'obchodni_oznaceni' => null,
			'vyrobce_vozidla' => null,
			'vyrobce_motoru' => null,
			'typ_motoru' => null,
			'max_vykon_kw_min' => null,
			'palivo' => null,
			'zdvihovy_objem_cm3' => 0,
			'plne_elektricke_vozidlo' => null,
			'hybridni_vozidlo' => null,
			'trida_hybridniho_vozidla' => null,
			'emisni_limit_ehkosn_ehses' => null,
			'stupen_plneni_emisni_urovne' => null,
			'korrigovany_soucin_absorpce' => null,
			'co2_mesto_mimo_kombi_gkm' => null,
			'specificke_co2' => null,
			'snizeni_emisi_nedc' => null,
			'snizeni_emisi_wltp' => null,
			'spotreba_predpis' => null,
			'spotreba_mesto_mimo_kombi_l100km' => null,
			'spotreba_pri_rychlosti_l100km' => null,
			'spotreba_el_mobil_whkm_z' => null,
			'dojezd_zr_km' => null,
			'vyrobce_karoserie' => null,
			'druh_typ' => null,
			'vyrobni_cislo_karoserie' => null,
			'barva' => null,
			'barva_doplnkova' => null,
			'pocet_mist_celkem_sezeni_stani' => null,
			'celkova_delka_sirka_vyska_mm' => null,
			'rozvor_mm' => null,
			'rozchod_mm' => null,
			'provozni_hmotnost' => null,
			'nejvetsi_tech_povolena_hmotnost_kg' => 0,
			'nejvetsi_tech_hmotnost_naprava_kg' => null,
			'nejvetsi_tech_hmotnost_pripoj_brzdene_kg' => null,
			'nejvetsi_tech_hmotnost_pripoj_nebrzdene_kg' => null,
			'nejvetsi_tech_hmotnost_soupravy_kg' => null,
			'hmotnosti_wltp' => null,
			'prumerna_uzitecne_zatizeni' => null,
			'spojovaci_zarizeni_druh' => null,
			'pocet_naprav_pohanenych' => null,
			'kola_pneumatiky_rozmery_montaz' => null,
			'hluk_vozidla_dba_stojici_ot_min' => null,
			'za_jizdy' => null,
			'nejvyssi_rychlost_kmh' => null,
			'pomer_vykon_hmotnost_kwkg' => null,
			'inovativni_technologie' => null,
			'stupen_dokonceni' => null,
			'faktor_odchylky_de' => null,
			'faktor_verifikace_vf' => null,
			'ucel_vozidla' => null,
			'dalsi_zaznamy' => null,
			'alternativni_provedeni' => null,
			'cislo_tp' => null,
			'cislo_orv' => null,
			'druh_rz' => null,
			'zarazeni_vozidla' => null,
			'status' => null,
			'abs' => null,
			'airbag' => null,
			'asr' => null,
			'brzdy_nouzova' => null,
			'brzdy_odlehcovaci' => null,
			'brzdy_parkovaci' => null,
			'brzdy_provozni' => null,
			'dopl_text_na_tp' => null,
			'hmotnosti_provozni_do' => null,
			'hmotnosti_zatez_sz' => null,
			'hmotnosti_zatez_sz_typ' => null,
			'hydropohon' => null,
			'objem_cisterny' => null,
			'zatez_strechy' => 0,
			'cislo_motoru' => null,
			'nejvyssi_rychlost_omezeni' => null,
			'ovladani_brz_sz' => null,
			'ovladani_brz_sz_druh' => null,
			'retarder' => null,
			'rok_vyroby' => 1900,
			'delka_do' => null,
			'lozna_delka' => null,
			'lozna_sirka' => null,
			'vyska_do' => null,
			'typ_kod' => null,
			'rm_zaniku' => null,
		];
	}
}
